export const usersbreakdown = [
  {
    name: "Alice Johnson",
    gender: "Female",
    industry: "Technology",
    role: "Enhanced",
    region: "North America",
    revenue: 12000,
    image: "https://randomuser.me/api/portraits/women/44.jpg",
  },
  {
    name: "Bob Smith",
    gender: "Male",
    industry: "Finance",
    role: "Basic",
    region: "Europe",
    revenue: 8500,
    image: "https://randomuser.me/api/portraits/men/46.jpg",
  },
  {
    name: "Carol Lee",
    gender: "Female",
    industry: "Healthcare",
    role: "Enhanced",
    region: "Asia",
    revenue: 9500,
    image: "https://randomuser.me/api/portraits/women/65.jpg",
  },
  {
    name: "David Kim",
    gender: "Male",
    industry: "Retail",
    role: "Basic",
    region: "South America",
    revenue: 6700,
    image: "https://randomuser.me/api/portraits/men/53.jpg",
  },
  {
    name: "Eva Green",
    gender: "Female",
    industry: "Education",
    role: "Enhanced",
    region: "Australia",
    revenue: 10200,
    image: "https://randomuser.me/api/portraits/women/28.jpg",
  },
];
